SELECT GETDATE() AS CURRENTDATE

SELECT GETDATE() AS CURRENTDATE,DATEPART(YEAR,GETDATE()) AS CURRENTYEAR ,
DATEPART(MONTH,GETDATE()) AS CURRENTMONTH,DATEPART(DAY,GETDATE()) AS CURRENTDAY

SELECT DATEDIFF(DAY, '2024-01-01', GETDATE())
AS DaysSinceNewYear
SELECT DATEDIFF(YEAR, '2024-01-01', GETDATE())

SELECT DATEDIFF(MONTH, '2024-01-01', GETDATE())
AS DaysSinceNewYear

SELECT DATEADD(DAY,   -30, GETDATE()) AS In30Days;

SELECT AGE(CURRENT_DATE,'2024-01-01')
SELECT * FROM [dbo].[T_EMPLOYEE]

SELECT SUM(SALARY) TOTALSAL FROM [dbo].[T_EMPLOYEE]
SELECT AVG(SALARY) TOTALSAL FROM [dbo].[T_EMPLOYEE]

SELECT COUNT(*) TOTALSAL FROM [dbo].[T_EMPLOYEE]
SELECT MIN(SALARY) TOTALSAL FROM [dbo].[T_EMPLOYEE]
SELECT MAX(SALARY) TOTALSAL FROM [dbo].[T_EMPLOYEE]

SELECT TOP(3) * FROM [dbo].[Products] ORDER BY PRICE
SELECT TOP(3) * FROM [dbo].[Products] ORDER BY PRICE DESC

SELECT CATEGORY,SUM(PRICE) TOTAL_PRICE FROM [dbo].[Products] GROUP BY CATEGORY


SELECT CATEGORY,COUNT(*) TOTAL_PRODUCTS FROM [dbo].[Products]  GROUP BY CATEGORY HAVING COUNT(*)>2 ORDER BY TOTAL_PRODUCTS DESC

SELECT COUNT(*) TOTAL_PRODUCTS FROM [dbo].[Products]


SELECT CATEGORY AS CAT FROM [dbo].[Products] WHERE CATEGORY ='Electronics'


SELECT COL FROM TBALE WHERE EXISTS(SELECT 1 FROM TABLE2 WHERE CONNDITION)

SELECT * FROM EMP E WHERE EXISTS (SELECT 1 FROM DEP D WHERE E.DEP_ID = D.DEP_ID)

SELECT 1







