DROP TABLE [dbo].[EMPLYOYEE]


CREATE TABLE EMP 
(
ID INT PRIMARY KEY,
NAME VARCHAR(MAX) NOT NULL,
SALARY FLOAT NOT NULL,
EMAIL_ID VARCHAR(255) UNIQUE

)


INSERT INTO EMP VALUES(1,'PRASHANT',267888,'PR@GMAIL.COM')

INSERT INTO EMP(ID,NAME,SALARY) VALUES(2,'ANANT',268880)
SELECT * FROM EMP

INSERT INTO EMP VALUES(3,'LUCKY',26788809,'LUKKY@GMAIL.COM')


INSERT INTO EMP(ID,NAME,SALARY,EMAIL_ID) VALUES(4,'RAHUL',2688789,'RAHUL@YAHOO.COM')


CREATE TABLE DEPARTMENT
(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(30) NOT NULL,
ID INT,
FOREIGN KEY(ID) REFERENCES EMP(ID)
)
SELECT * FROM DEPARTMENT
INSERT INTO DEPARTMENT VALUES(100,'IT',1)

INSERT INTO DEPARTMENT VALUES(101,'HR',4)

SELECT * FROM EMP E LEFT JOIN DEPARTMENT D ON E.ID=D.ID
